-- 1. Aşama 
--select city, country from city
--left join country on city.country_id= country.country_id
-- 2. Aşama 
--select first_name, last_name, payment_id from customer
--right join payment on customer.customer_id= payment.customer_id
--order by payment_id
-- 3. aşama
--select first_name, last_name, rental_id from customer 
--full join rental on customer.customer_id= rental.customer_id
-- order by rental_id

